SPORT_CATEGORY_MAP = {
    # Foot sports
    "Run": "Foot sports",
    "TrailRun": "Foot sports",
    "VirtualRun": "Foot sports",
    "Walk": "Foot sports",
    "Hike": "Foot sports",
    "Wheelchair": "Foot sports",
    # Cycle sports
    "Ride": "Cycle sports",
    "GravelRide": "Cycle sports",
    "MountainBikeRide": "Cycle sports",
    "EMountainBikeRide": "Cycle sports",
    "EBikeRide": "Cycle sports",
    "VirtualRide": "Cycle sports",
    "Handcycle": "Cycle sports",
    "Velomobile": "Cycle sports",
    # Water sports
    "Swim": "Water sports",
    "Surfing": "Water sports",
    "StandUpPaddling": "Water sports",
    "Rowing": "Water sports",
    "Canoeing": "Water sports",
    "Kayaking": "Water sports",
    "Kitesurf": "Water sports",
    "Windsurf": "Water sports",
    "Sail": "Water sports",
    # Winter sports
    "AlpineSki": "Winter sports",
    "BackcountrySki": "Winter sports",
    "NordicSki": "Winter sports",
    "RollerSki": "Winter sports",
    "Snowboard": "Winter sports",
    "Snowshoe": "Winter sports",
    "IceSkate": "Winter sports",
    # Other
    "Soccer": "Other",
    "Tennis": "Other",
    "TableTennis": "Other",
    "Badminton": "Other",
    "Squash": "Other",
    "Racquetball": "Other",
    "Pickleball": "Other",
    "Golf": "Other",
    "Yoga": "Other",
    "Pilates": "Other",
    "WeightTraining": "Other",
    "Workout": "Other",
    "Crossfit": "Other",
    "HighIntensityIntervalTraining": "Other",
    "Elliptical": "Other",
    "StairStepper": "Other",
    "RockClimbing": "Other",
    "Skateboard": "Other",
    "InlineSkate": "Other",
    "VirtualRow": "Other",
}

MONTHS_LABELS = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
]

MONTHS_MAP = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December",
}

DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
